### ISSUE TITLE
QrDetector Exception

### ISSUE THREAD

**Issue by vladaman** [contactlutforrahman/flutter_qr_bar_scanner#44]
Production version apk released to google play throws an exception:

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
       at com.github.contactlutforrahman.flutter_qr_bar_scanner.QrDetector.onSuccess(QrDetector.java:14)
       at com.github.contactlutforrahman.flutter_qr_bar_scanner.QrDetector.onSuccess(QrDetector.java:2)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7889)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Versions:

```
flutter_qr_bar_scanner: ^3.0.2
google_ml_kit: ^0.9.0
```

**Comment by vladaman** [comment]
Also after migrating to separate external dependencies I get different error:

```yaml
# pubspec.yaml
  google_mlkit_object_detection: ^0.3.0
  google_mlkit_text_recognition: ^0.3.0
  google_mlkit_image_labeling: ^0.3.0
```

```
E/AndroidRuntime(19183): java.lang.VerifyError: Verifier rejected class com.google.mlkit.vision.barcode.BarcodeScanning: com.google.mlkit.vision.barcode.BarcodeScanner com.google.mlkit.vision.barcode.BarcodeScanning.getClient() failed to verify: com.google.mlkit.vision.barcode.BarcodeScanner com.google.mlkit.vision.barcode.BarcodeScanning.getClient(): [0x10]  can't resolve returned type 'Unresolved Reference: com.google.mlkit.vision.barcode.BarcodeScanner' or 'Unresolved Reference: com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl'
E/AndroidRuntime(19183):  com.google.mlkit.vision.barcode.BarcodeScanner com.google.mlkit.vision.barcode.BarcodeScanning.getClient(com.google.mlkit.vision.barcode.BarcodeScannerOptions) failed to verify: com.google.mlkit.vision.barcode.BarcodeScanner com.google.mlkit.vision.barcode.BarcodeScanning.getClient(com.google.mlkit.vision.barcode.BarcodeScannerOptions): [0x15]  can't resolve returned type 'Unresolved Reference: com.google.mlkit.vision.barcode.BarcodeScanner' or 'Unresolved Reference: com.google.mlkit.vision.barcode.internal.BarcodeScannerImpl' (declaration of 'com.google.mlkit.vision.barcode.BarcodeScanning' appears in /data/app/~~gW1AnoT1VFocTiFfSvPHmw==/eu.fbXdDphC-UL9lhauTQ==/base.apk!classes7.dex)
E/AndroidRuntime(19183): 	at com.google.mlkit.vision.barcode.BarcodeScanning.getClient(com.google.android.gms:play-services-mlkit-barcode-scanning@@16.1.4:2)
E/AndroidRuntime(19183): 	at com.github.contactlutforrahman.flutter_qr_bar_scanner.QrDetector.<init>(QrDetector.java:41)
E/AndroidRuntime(19183): 	at com.github.contactlutforrahman.flutter_qr_bar_scanner.QrReader.<init>(QrReader.java:31)
E/AndroidRuntime(19183): 	at com.github.contactlutforrahman.flutter_qr_bar_scanner.FlutterQrBarScannerPlugin.onMethodCall(FlutterQrBarScannerPlugin.java:174)
E/AndroidRuntime(19183): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(19183): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(19183): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19183): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(19183): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/AndroidRuntime(19183): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19183): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/AndroidRuntime(19183): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by toprako** [comment]
@vladaman  Hello, did you solve the error?

**Comment by mazhiyuam** [comment]
found same crash, any solutions please?
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;

**Comment by toprako** [comment]
Unfortunately, there is no solution, so I changed libraries.
