### ISSUE TITLE
Scanner crashes when using latest flutter. 

### ISSUE THREAD

**Issue by pneves001** [contactlutforrahman/flutter_qr_bar_scanner#52]
The ml dependency is out of date: 
This is the new version. 

implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.1.0'

**Comment by pneves001** [comment]
I/BufferQueue(18803): [unnamed-18803-0](this:0x7cd247b800,id:0,api:0,p:-1,c:-1) BufferQueue core=(18803:com.nevessoftware.neves_wallet)
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(18803): [unnamed-18803-0](this:0x7cd247b800,id:0,api:0,p:-1,c:18803) connect(C): consumer=(18803:com.nevessoftware.neves_wallet) controlledByApp=true
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(18803): [unnamed-18803-0](this:0x7cd247b800,id:0,api:0,p:-1,c:18803) setConsumerName: unnamed-18803-0
W/re.neves_wallet(18803): type=1400 audit(0.0:87603): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=197 scontext=u:r:untrusted_app:s0:c217,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(18803): [SurfaceTexture-0-18803-0](this:0x7cd247b800,id:0,api:0,p:-1,c:18803) setConsumerName: SurfaceTexture-0-18803-0
W/re.neves_wallet(18803): type=1400 audit(0.0:87604): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=197 scontext=u:r:untrusted_app:s0:c217,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/cgr.qrmv.QrReader(18803): Using new camera API.
W/DynamiteModule(18803): Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
W/DynamiteModule(18803): Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
W/DynamiteModule(18803): Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
D/TransportRuntime.JobInfoScheduler(18803): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=578759062 in 30000ms(Backend next call timestamp 1663807158136). Attempt 1
D/TransportRuntime.JobInfoScheduler(18803): Scheduling upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=583739799 in 86400000ms(Backend next call timestamp 0). Attempt 1
I/CameraManagerGlobal(18803): Connecting to camera service
I/CameraManagerGlobal(18803): change camera ids
D/CameraManager(18803):  pixelArraySize.width/heigh=4208  3120
I/chatty  (18803): uid=10217(com.nevessoftware.neves_wallet) identical 1 line
D/CameraManager(18803):  pixelArraySize.width/heigh=4208  3120
D/TransportRuntime.SQLiteEventStore(18803): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(18803): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
I/BufferQueue(18803): [unnamed-18803-1](this:0x7c55471000,id:1,api:0,p:-1,c:-1) BufferQueue core=(18803:com.nevessoftware.neves_wallet)
W/re.neves_wallet(18803): type=1400 audit(0.0:87606): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=197 scontext=u:r:untrusted_app:s0:c217,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(18803): [unnamed-18803-1](this:0x7c55471000,id:1,api:0,p:-1,c:18803) connect(C): consumer=(18803:com.nevessoftware.neves_wallet) controlledByApp=true
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
W/re.neves_wallet(18803): type=1400 audit(0.0:87607): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=197 scontext=u:r:untrusted_app:s0:c217,c256,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/BufferQueueConsumer(18803): [unnamed-18803-1](this:0x7c55471000,id:1,api:0,p:-1,c:18803) setConsumerName: unnamed-18803-1
E/libc    (18803): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(18803): [ImageReader-4896x2448f23m5-18803-0](this:0x7c55471000,id:1,api:0,p:-1,c:18803) setConsumerName: ImageReader-4896x2448f23m5-18803-0
I/BufferQueueConsumer(18803): [ImageReader-4896x2448f23m5-18803-0](this:0x7c55471000,id:1,api:0,p:-1,c:18803) setDefaultBufferSize: width=4896 height=2448
I/BufferQueueConsumer(18803): [SurfaceTexture-0-18803-0](this:0x7cd247b800,id:0,api:0,p:-1,c:18803) setDefaultBufferSize: width=4896 height=2448
I/cgr.qrmv.QrCameraC2(18803): Setting af mode to: 3
I/DynamiteModule(18803): Considering local module com.google.android.gms.vision.barcode:0 and remote module com.google.android.gms.vision.barcode:2
I/DynamiteModule(18803): Selected remote version of com.google.android.gms.vision.barcode, version >= 2
V/DynamiteModule(18803): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/BufferQueueProducer(18803): [ImageReader-4896x2448f23m5-18803-0](this:0x7c55471000,id:1,api:4,p:668,c:18803) connect(P): api=4 producer=(668:???) producerControlledByApp=false
I/BufferQueueProducer(18803): [SurfaceTexture-0-18803-0](this:0x7cd247b800,id:0,api:4,p:668,c:18803) connect(P): api=4 producer=(668:???) producerControlledByApp=true
W/Gralloc3(18803): allocator 3.x is not supported
I/NDOP    (18803): listening using window listener
E/ion     (18803): ioctl c0044901 failed with code -1: Invalid argument
W/re.neves_walle(18803): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk*876013269:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes2.dex*1672639879:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes3.dex*2071137768:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes4.dex*4123225371:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes5.dex*2357261182:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes6.dex*1441110153:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes7.dex*3951089511:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes8.dex*1477735997:/data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk!classes9.dex*2818058189]{PCL[/system/framework/org.apache.http.legacy.jar*1921091862]})
W/re.neves_walle(18803): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000164/dl-VisionBarcodeDynamite.integ_221180404100400.apk
W/re.neves_walle(18803): NOTE: This wastes RAM and hurts startup performance.
W/re.neves_walle(18803): Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/00000164/dl-VisionBarcodeDynamite.integ_221180404100400.apk
W/re.neves_walle(18803): 
W/LibraryVersion(18803): Failed to get app version for libraryName: optional-module-barcode
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
I/NDOP    (18803): listening using window listener
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
I/NDOP    (18803): listening using window listener
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
I/NDOP    (18803): listening using window listener
D/TransportRuntime.SQLiteEventStore(18803): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
D/TransportRuntime.JobInfoScheduler(18803): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
I/NDOP    (18803): listening using window listener
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/re.neves_walle(18803): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
I/NDOP    (18803): listening using window listener
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
I/NDOP    (18803): listening using window listener
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
I/NDOP    (18803): listening using window listener
E/IMGSRV  (18803): :0: IsTextureConsistent: IMGEGLImage is not consistent
I/NDOP    (18803): listening using window listener
W/DynamiteModule(18803): Local module descriptor class for com.google.android.gms.tflite_dynamite not found.
E/IMGSRV  (18803): :0: glEGLImageTargetTexture2DOES: the dimensions of the IMGEGLImage exceed the allowable dimensions for a texture
E/IMGSRV  (18803): :0: glEGLImageTargetTexture2DOES: the dimensions of the IMGEGLImage exceed the allowable dimensions for a texture
E/OpenGLRenderer(18803): [SurfaceTexture-0-18803-0] bindTextureImage: error binding external image: 0x502
I/DynamiteModule(18803): Considering local module com.google.android.gms.tflite_dynamite:0 and remote module com.google.android.gms.tflite_dynamite:222506100
I/DynamiteModule(18803): Selected remote version of com.google.android.gms.tflite_dynamite, version >= 222506100
E/flutter (18803): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (18803): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (18803): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
E/flutter (18803): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter (18803): 
F/flutter (18803): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env). 
F/libc    (18803): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18834 (1.raster), pid 18803 (re.neves_wallet)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Ulefone/Armor_X8/Armor_X8:10/QP1A.190711.020/1598255144:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-09-22 10:55:08-0700
pid: 18803, tid: 18834, name: 1.raster  >>> com.nevessoftware.neves_wallet <<<
uid: 10217
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  0000000000004992  x2  0000000000000006  x3  0000007c73947d50
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000080
    x8  00000000000000f0  x9  0000007d67509520  x10 0000000000000000  x11 0000000000000001
    x12 0000000006f5ca90  x13 0000000000000003  x14 0000000000000001  x15 0000000000000000
    x16 0000007d675d78c0  x17 0000007d675b44f0  x18 0000007c72d10000  x19 00000000000000ac
    x20 0000000000004973  x21 00000000000000b2  x22 0000000000004992  x23 00000000ffffffff
    x24 0000007cd66ea840  x25 0000000000000000  x26 0000000000000001  x27 0000000000000040
    x28 0000000000000001  x29 0000007c73947e00
    sp  0000007c73947d30  lr  0000007d675684c8  pc  0000007d675684f8
backtrace:
      #00 pc 00000000000834f8  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 4a8e31896b542a160fa1f1dae43732e7)
      #01 pc 00000000015bc44c  /data/app/com.nevessoftware.neves_wallet-5TVHqXHSyw5DZ_hYSgGvyQ==/lib/arm64/libflutter.so (BuildId: 36a3f11c2e8288daf999b421e4196bf50667cb80)
Lost connection to device.

**Comment by pneves001** [comment]
I need this to work with a mminSdkVersion=21 and targetSdkVersion=30 since other plugins I  am using require this.

**Comment by liudonjun** [comment]
You need to check your code to make sure you don't handle image sizes that exceed the device's maximum texture size. If you don't have control over the dimensions of the image, you may need to scale or crop the image before processing it.
